name: Renovate
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      
